// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://sgaztfwzdbdbmqldgsqm.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnYXp0Znd6ZGJkYm1xbGRnc3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NTgzMjEsImV4cCI6MjA0ODAzNDMyMX0.-9279W7pvNboZhIbjpLr0XYG-jr13mgt53OPugtanrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);